version: '3.7'
services:
  db:
    container_name: dronetag_db
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    container_name: dronetag
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .env
    restart: always
    ports:
      - '8000:8000'
    volumes:
     - .:/app
     - static_volume:/app/external_storage/static
     - media_volume:/app/external_storage/media
     - logs:/app/external_storage/logs
    depends_on:
      - db

volumes:
  static_volume:
  media_volume:
  postgres_data:
  logs:
