# Generated by Django 5.0.3 on 2024-03-17 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('statuses', '0003_alter_statusdataset_data'),
        ('telemetry', '0003_alter_telemetrydataset_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightAnalytics',
            new_name='FlightAnalyticsDataset',
        ),
    ]
