# Generated by Django 5.0.3 on 2024-03-12 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('data', models.FileField(upload_to='status/', verbose_name='Raw data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_status_datasets', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Status dataset',
                'verbose_name_plural': 'Status datasets',
            },
        ),
        migrations.CreateModel(
            name='StatusDatapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveBigIntegerField(verbose_name='External ID')),
                ('flight_id', models.CharField(max_length=36, verbose_name='Flight ID')),
                ('time', models.DateTimeField(help_text='Datapoint time', verbose_name='Time')),
                ('time_received', models.DateTimeField(help_text='Time when this message was received on server.', verbose_name='Time received')),
                ('battery_v', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Battery voltage [V]')),
                ('cell_id', models.CharField(help_text='ID of the current LTE cell station.', max_length=8, verbose_name='Cell ID')),
                ('rsrp_dbm', models.SmallIntegerField(help_text='Reference Signal Received Power of LTE in decibelmiliwatts (dBm).', verbose_name='RSRP [dBm]')),
                ('rsrq_db', models.SmallIntegerField(help_text='Reference Signal Received Quality of LTE in decibels (dB).', verbose_name='RSRQ [dB]')),
                ('snr_db', models.SmallIntegerField(help_text='Signal to Noise Ratio of LTE in decibels (dB).', verbose_name='SNR [dB]')),
                ('tac', models.CharField(help_text='Tracking Area Code of LTE.', max_length=4, verbose_name='TAC')),
                ('visible_satellites_num', models.PositiveSmallIntegerField(verbose_name='Number of visible GNSS satellites')),
                ('is_charging', models.BooleanField(verbose_name='Charging?')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='statuses.statusdataset', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Status datapoint',
                'verbose_name_plural': 'Status datapoints',
                'unique_together': {('dataset', 'external_id'), ('external_id', 'flight_id')},
            },
        ),
    ]
