COORDINATE_PRECISION = 15
LATITUDE_DIGITS = 2 + COORDINATE_PRECISION
LONGITUDE_DIGITS = 3 + COORDINATE_PRECISION

ALTITUDE_PRECISION = 2
ALTITUDE_DIGITS = 4 + ALTITUDE_PRECISION  # that is frickin high

HEIGHT_PRECISION = 2
HEIGHT_DIGITS = 4 + HEIGHT_PRECISION  # that is frickin high

VELOCITY_PRECISION = 16
VELOCITY_DIGITS = 3 + VELOCITY_PRECISION  # that is frickin fast (sanic!)

PRESSURE_PRECISION = 13
PRESSURE_DIGITS = 4 + PRESSURE_PRECISION
