# Generated by Django 5.0.3 on 2024-03-09 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('data', models.FileField(upload_to='telemetry/', verbose_name='Raw data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_telemetry_datasets', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Telemetry dataset',
                'verbose_name_plural': 'Telemetry datasets',
            },
        ),
        migrations.CreateModel(
            name='TelemetryDatapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveBigIntegerField(verbose_name='External ID')),
                ('time', models.DateTimeField(help_text='Datapoint time', verbose_name='Time')),
                ('time_received', models.DateTimeField(help_text='Time when this message was received on server.', verbose_name='Time received')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Longitude')),
                ('altitude_m', models.DecimalField(decimal_places=2, help_text='Altitude calculated from pressure sensor (QNH referece) in meters', max_digits=6, verbose_name='Altitude [m]')),
                ('geo_altitude_m', models.DecimalField(decimal_places=2, help_text='Altitude supplied from the GNSS received (geoid reference) in meters.', max_digits=6, verbose_name='Geo altitude [m]')),
                ('height_m', models.DecimalField(decimal_places=2, help_text='Relative altitude from the takeoffpoint in meters.', max_digits=6, verbose_name='Height [m]')),
                ('velocity_x_ms', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='X velocity [m/s]')),
                ('velocity_y_ms', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='Y velocity [m/s]')),
                ('velocity_z_ms', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='Z velocity [m/s]')),
                ('vertical_accuracy_m', models.PositiveSmallIntegerField(verbose_name='Vertical accuracy [m]')),
                ('horizontal_accuracy_m', models.PositiveSmallIntegerField(verbose_name='Horizontal accuracy [m]')),
                ('velocity_accuracy_ms', models.PositiveSmallIntegerField(verbose_name='Velocity accuracy [m/s]')),
                ('pressure_hpa', models.DecimalField(decimal_places=13, max_digits=17, verbose_name='Pressure [hPa]')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='telemetry.telemetrydataset', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Telemetry datapoint',
                'verbose_name_plural': 'Telemetry datapoints',
                'unique_together': {('dataset', 'external_id')},
            },
        ),
    ]
