# Generated by Django 5.0.3 on 2024-03-12 16:08

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_telemetrydataset_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrydataset',
            name='data',
            field=models.FileField(upload_to=common.models.resolve_data_path, verbose_name='Raw data'),
        ),
    ]
