# Generated by Django 5.0.3 on 2024-03-18 09:23

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_alter_telemetrydataset_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrydatapoint',
            name='latency',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('time_received'), '-', models.F('time')), output_field=models.DurationField()),
        ),
    ]
